spring:
  jpa:    hibernate:      ddl-auto: update
  application:
    name: blog  datasource:
    username: crydion    password: crydion
server:
  port: 8080
analyzer:
  ribbon:
    listOfServers: localhost:8081