apiVersion: v1
kind: Service
metadata:
  name: analyzer
spec:
  ports:
  - port: 8081
  selector:
    app: analyzer
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
      - image: munizva/analyzer
        name: analyzer
        ports:
        - containerPort: 8081
          name: analyzer
