apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  ports:
  - port: 8080
    nodePort: 30000
  selector:
    app: blog
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: munizva/blog
        name: blog
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: crydion
        - name: SPRING_DATASOURCE_PASSWORD
          value: crydion
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db/blog
        - name: ANALYZER_RIBBON_LISTOFSERVERS
          value: analyzer:8081
        ports:
        - containerPort: 8080
          name: blog
